1. Write a NumPy program to capitalize the first letter, lowercase, uppercase, swapcase, title-case of all the elements of a given array.
Expected Output:
Original Array:
['python' 'PHP' 'java' 'C++']
Capitalized: ['Python' 'Php' 'Java' 'C++']
Lowered: ['python' 'php' 'java' 'c++']
Uppered: ['PYTHON' 'PHP' 'JAVA' 'C++']
Swapcased: ['PYTHON' 'php' 'JAVA' 'c++']
Titlecased: ['Python' 'Php' 'Java' 'C++']

In [1]:
import numpy as np
a=np.array(['python', 'PHP', 'java', 'C++'])
print(a)
b=np.char.upper(a)
print(b)
c=np.char.lower(a)
print(c)
d=np.char.capitalize(a)
print(d)
e=np.char.swapcase(a)
print(e)

['python' 'PHP' 'java' 'C++']
['PYTHON' 'PHP' 'JAVA' 'C++']
['python' 'php' 'java' 'c++']
['Python' 'Php' 'Java' 'C++']
['PYTHON' 'php' 'JAVA' 'c++']


2. Write a NumPy program to check whether each element of a given array starts with "K"
Input: any one Sentence

In [2]:
import numpy as np
a=np.array(['A','B','C','D','kamal','k','kin'])
for i in range(len(a)):
    if (a[i][0]=="k" or a[i][0]=="K"):
        print("Element starts with k and the element is--->",a[i])
    else:
        pass

Element starts with k and the element is---> kamal
Element starts with k and the element is---> k
Element starts with k and the element is---> kin


3. Write a NumPy program to count a given word in each row of a given array of string values.
Sample output:
Original array of string values:
[['Python' 'NumPy' 'Exercises']
['Python' 'Pandas' 'Exercises']
['Python' 'Machine learning' 'Python']]
Count 'Python' row wise in the above array of string values:
[[1 0 0]
[1 0 0]
[1 0 1]]

In [3]:
a=np.array([['Python', 'NumPy', 'Exercises'],['Python', 'Pandas', 'Exercises'],['Python', 'Machine learning', 'Python']])
b=input("enter to find:")
c=np.zeros((3,3))
for i in range(len(a)):
    for j in range(len(a[i])):
        if (a[i][j]==b):
            c[i][j]=1
    else:
        pass
print(c)

enter to find:NumPy
[[0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


4. Write a NumPy python program to find common values between two arrays.
Expected Output:
Array1: [ 0 10 20 40 60]
Array2: [10, 30, 40]
Common values between two arrays:
[10 40]

In [4]:
a=np.array([0,10,20,40,60])
b=np.array([10, 30, 40])
c=[]
for i in range(len(a)):
    for j in range(len(b)):
        if(a[i]==b[j]):
            c.append(a[i])
            print(a[i])
        else:
            pass
print(c)

10
40
[10, 40]


5. Write a NumPy program to split of an array of shape 4x4 it into two arrays along the second axis
Sample array :
Sample array :
[[ 0 1 2 3]
........
[12 13 14 15]]
Expected Output:
[array([[ 0, 1],
[ 4, 5],
[ 8, 9],
[12, 13]]), array([[ 2, 3],
[ 6, 7],
[10, 11],
[14, 15]]), array([], shape=(4, 0), dtype=int64)]

In [5]:
a=np.arange(0,16).reshape(4,4)
[b,c]=np.hsplit(a,2)
print(a)
print(b)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
