In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])

In [3]:
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.dtype

dtype('int32')

In [6]:
a.ndim

1

In [7]:
a.size

3

In [8]:
a.shape

(3,)

In [9]:
b = np.array([[1.3, 2.4],[0.3, 4.1]])

In [10]:
b.dtype

dtype('float64')

In [11]:
b.ndim

2

In [12]:
b.size

4

In [13]:
b.shape

(2, 2)

In [14]:
b.itemsize

8

In [15]:
c = np.array([[1, 2, 3],[4, 5, 6]])

In [16]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
d = np.array(((1, 2, 3),(4, 5, 6)))

In [18]:
d

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
e = np.array([(1, 2, 3), [4, 5, 6], (7, 8, 9)])

In [20]:
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
g = np.array([['a', 'b'],['c', 'd']])

In [23]:
print(g)

[['a' 'b']
 ['c' 'd']]


In [24]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(0, 6, 0.6)

array([0. , 0.6, 1.2, 1.8, 2.4, 3. , 3.6, 4.2, 4.8, 5.4])

In [28]:
np.arange(0, 12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [30]:
np.random.random(3)

array([0.2747976 , 0.01280858, 0.46743341])

In [31]:
np.random.random((3,3))

array([[0.47203211, 0.67712558, 0.07004074],
       [0.38149539, 0.284715  , 0.24910596],
       [0.79931499, 0.31859909, 0.63653625]])

In [32]:
a = np.arange(4)

In [33]:
a

array([0, 1, 2, 3])

In [37]:
#Create 2D numpy array using arange() function.
import numpy as np
a=np.arange(0,8).reshape(2,4)
print(a)

[[0 1 2 3]
 [4 5 6 7]]


In [38]:
#Create 3D array from 1D numpy array.
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])
d=np.array([a,b,c])
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
#Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.
import numpy as np
a=np.arange(2,11).reshape(3,3)
print(a)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [51]:
#Write a NumPy program to reverse an array (first element becomes last).
import numpy as np
a=np.arange(1,6)
b=a[::-1]
print(a)
print("--------------")
print(b)

[1 2 3 4 5]
--------------
[5 4 3 2 1]


[[1. 1.]
 [1. 1.]]


In [66]:
#Create a 2D array A with 4x4 size then split it into 3 different arrays B(1x4),C(2x4) and D(2x4).
A=np.arange(1,17).reshape(4,4)
print(A)
B=np.vsplit(A,1)
[C,D] = np.vsplit(A,2)
print(B)
print(C)
print(D)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])]
[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]


In [67]:
#Perform element wise multiplication of arrays C and D in question 6.
A=np.arange(1,17).reshape(4,4)
print(A)
[C,D] = np.vsplit(A,2)
print(C)
print(D)
print(C*4)
print(D*5)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]
[[ 4  8 12 16]
 [20 24 28 32]]
[[45 50 55 60]
 [65 70 75 80]]


In [116]:
#Create a numpy array matrix of size 3x4. Find column which has highest sum and display.
a = np.arange(10,22).reshape(3,4)
print(a)
[c,d,e,f]=np.hsplit(a,4)
sum_1=c.sum()
sum_2=d.sum()
sum_3=e.sum()
sum_4=f.sum()
print(" Col 1 sum=",sum_1,'\n',"Col 2 sum=",sum_2,'\n',"Col 3 sum=",sum_3,'\n',"Col 4 sum=",sum_4)
if sum_1>sum_2 and sum_1>sum_3 and sum_1>sum_4:
    print("Col 1 is greatest")
elif sum_4>sum_1 and sum_4>sum_2 and sum_4>sum_3:
    print("Col 4 is greatest")

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
 Col 1 sum= 42 
 Col 2 sum= 45 
 Col 3 sum= 48 
 Col 4 sum= 51
Col 4 is greatest


In [4]:
#Greatest of 3 numbers
c=int(input("Enter a number:"))
d=int(input("Enter a number:"))
e=int(input("Enter a number:"))
if e>c and e>d:
    print("greatest is e->",e)
elif d>e and d>c:
    print("greatest is d->",d)
elif c>e and c>d:
    print("greatest is c->",c)
else:
    print("equal")

Enter a number:20
Enter a number:21
Enter a number:22
greatest is e-> 22
